name: dino-ai
channels:
  - conda-forge
dependencies:
  - jupyter
  - pandas
  - matplotlib
  - stable-baselines3[extra]
  - opencv
  - python=3.10
  - pytesseract
  - protobuf
  - tqdm
  - black

# conda install pytorch torchvision torchaudio -c pytorch
# pip install mss pyautogui