name: rl
channels:
  - conda-forge
dependencies:
  - pytorch
  - torchvision
  - tensorboard
  - jupyter
  - pandas
  - matplotlib
  - stable-baselines3[extra]
  - opencv
  - tesseract
  - pytesseract
  - python=3.10
  - python-mss
  - protobuf
  - tqdm
  - black

# pip install pyautogui